version: 0.2

#  shell: /bin/bash
# run-as: root
env:
  variables:
    FROM_IMAGE: "debian"
    FROM_TAG: "10-slim"
    GHC_VER: "8.8.4"
    CABAL_VER: "3.2.0.0"
    IMAGE_NAME: "haskell"

phases:
  build:
    commands:
      - echo $FROM_IMAGE
      - echo $FROM_TAG
      - echo $GHC_VER
      - echo $CABAL_VER
      - echo $IMAGE_NAME
      - pwd
      - env

      - $(cd codebuild/haskell && ./codebuild.sh)
        #      - >
        #        docker build \
        #          --build-arg FROM_IMAGE=$FROM_IMAGE \
        #          --build-arg FROM_TAG=$FROM_TAG \
        #          --build-arg GHC_VER=$GHC_VER \
        #          --build-arg CABAL_VER=$CABAL_VER \
        #          -t mgreenly/$IMAGE_NAME:latest \
        #          .
